version: '3.8'
services:
  rocket-app:
    build:
      context: .
      dockerfile: Dockerfile # Le nom du fichier que tu viens de m'envoyer
    ports:
      - "3000:3000" # Frontend Next.js
      - "8000:8000" # Backend Rust
      - "8001:8001" # Service Python CEA
    restart: unless-stopped
