[package]
name = "rocket_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rocket_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.0", features = ["extension-module", "abi3-py310"] }
numpy = "0.22.0"
rand = "0.8.5"

[build-dependencies]
pyo3-build-config = "0.22.0"
